### ISSUE TITLE
Basic CSS documentation

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#49]
The next release should have some basic CSS documentation

**Comment by ousia** [comment]
Many thanks for the commit.

I’m afraid that the link in the [documentation](https://speedata.github.io/publisher/manual/index.html) points to the non-existing https://speedata.github.io/publisher/manual/description/css.html instead of https://speedata.github.io/publisher/manual/description-en/css.html.

**Comment by pgundlach** [comment]
The link is fixed now, but the example on the english description is in German... Will change that as well. Thanks a lot for the bug report!
