### ISSUE TITLE
Revise building instructions

### ISSUE THREAD

**Issue by pgundlach** [speedata/publisher#77]
The  building instructions might not be up to date. Make sure (on a clean linux system for example) that all steps are doumented.

**Comment by danielhjames** [comment]
Installation of binaries worked fine for me, but I could not find instructions for building from source except within the Rakefile. I could contribute some documentation about this topic once I have a working source build. Is there a minimum Go version supported?

**Comment by pgundlach** [comment]
These are the steps that worked for me on an Ubuntu 14.4 box:

* sudo apt-get install build-essentials
* sudo apt-get install git
* sudo apt-get install rake
* sudo apt-get install golang (Version 1.5 or higher, if lower then you need to edit the Rakefile and replace `-X foo=bar` with `-X foo bar`)
* git clone https://github.com/speedata/publisher.git
* rake build

And then: get a luatex binary from https://download.speedata.de/extra/ and copy it into the `bin/`directory of the publisher

**Comment by danielhjames** [comment]
Thanks Patrick, I had 'not a package file' errors when building from source until I made a fresh git clone, for some reason.

One suggestion: the package name on Debian/Ubuntu is build-essential rather than build-essentials, and it can be included on one line while installing the other packages and the luatex binary like so:

sudo apt-get install build-essential git rake golang texlive-binaries

The drawback to this approach is that the texlive-binaries package comes with a massive set of dependencies which Speedata probably doesn't need, so it's not ideal for a production server. I see that your own .deb package provides a luatex binary.

The version of golang in Debian stable (jessie) is quite old, version 1.3.3 from 2014. Version 1.6.2 can be installed with:

sudo apt-get install -t jessie-backports golang

as long as the jessie-backports repository is enabled in /etc/apt/sources.list 

Also, git clone over https is now a pain for newbies on Debian or Ubuntu because the root certificates for the SSL certs that GitHub uses are no longer included by default in these distros. There is the option to clone over git:// instead, of course.

I noticed that after building the manual on a server with only the console available, the sp doc command fails (because it cannot open a browser). As a workaround, the user can do something like:

elinks build/manual/index.html

where 'elinks' is any console-mode web browser.

Anyway, I will write up these notes for the wiki and send a pull request.

**Comment by pgundlach** [comment]
I am not sure that `texlive-binaries` is a good package to install, since I need version 0.79, and I doubt that this version is in there or stays in there. The binaries should be taken from the link I have provided (https://download.speedata.de/extra/luatex_079-win-mac-linux.zip) - I know this is not ideal, but I do need control over the version used.

It really sucks that the format of linking has changed in Go since 1.5 (?). I might make a change in the Rakefile to distinguish between these two different behaviours.

What is wrong with `git clone https://github.com/speedata/publisher.git`? It works fine on my current Ubuntu system (16.04 LTS). `git clone git://....` would be fine with me.

I think the command line should be `apt install build-essential git ....` as this seems to be the modern way of installing things (but I might be wrong in this case again)

Thank you vey much for your feedback!

**Comment by danielhjames** [comment]
Hi Patrick, on Debian jessie I get luatex beta-0.79.1 (TeX Live 2015) after installing texlive-binaries, but I can see from a QA point of view it would be better if users installed your exact luatex binary. 

Personally, I would use your APT repository version of the package for a production server, and the luatex binary that comes with it, as it's the easiest way to manage updates.

git clone https://github.com... now works for me on a clean Debian install. The issue was not the certificates, it was that when I reset my virtual server to a clean state, it also reset the server date to 2015!

You are right that 'apt install' does the job, it has fewer options than 'apt-get install' but is fine for this purpose.

**Comment by danielhjames** [comment]
I've updated https://github.com/speedata/publisher/wiki/Installation-instructions with a 'Build from source' option. These instructions worked fine for me on a clean Debian jessie server image, after updating golang to version 1.6.2.

**Comment by pgundlach** [comment]
This is really great! I mean it, thank you very much! I am thinking about putting these instructions into the main manual, may I use your text?

**Comment by danielhjames** [comment]
That is a good idea to put this in the manual, of course you are welcome to use anything I contribute in the project wherever. It might be good to have some contributor guidelines in the git repo, for other people. 

You can now use a pull request template so that contributors have to check a box to agree to use of their contribution: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by pgundlach** [comment]
I will keep this open until I have added the instructions to the manual.
